git-debimport lvm2_2.02.111-2.2.debian.tar.xz

diff --git a/debian/initramfs-tools/lvm2/scripts/local-block/lvm2 b/debian/initramfs-tools/lvm2/scripts/local-block/lvm2
--- a/debian/initramfs-tools/lvm2/scripts/local-block/lvm2
+++ b/debian/initramfs-tools/lvm2/scripts/local-block/lvm2
@@ -21,20 +21,28 @@ fi
 
 dev="$1"
 
-# Make sure that we have a d-m path
-dev="${dev#/dev/mapper/}"
-if [ "$dev" = "$1" ]; then
-	return 1
-fi
+case "$dev" in
+/dev/mapper/*)
+	dev="${dev#/dev/mapper/}"
 
-eval $(dmsetup splitname --nameprefixes --noheadings --rows "$dev")
+	eval $(dmsetup splitname --nameprefixes --noheadings --rows "$dev")
 
-if [ "$DM_VG_NAME" ] && [ "$DM_LV_NAME" ]; then
-	lvm lvchange -aly --ignorelockingfailure "$DM_VG_NAME/$DM_LV_NAME"
-	rc=$?
-	if [ $rc = 5 ]; then
-		echo "Unable to find LVM volume $DM_VG_NAME/$DM_LV_NAME"
+	if [ "$DM_VG_NAME" ] && [ "$DM_LV_NAME" ]; then
+		lvm lvchange -aly --ignorelockingfailure "$DM_VG_NAME/$DM_LV_NAME"
+		rc=$?
+		if [ $rc = 5 ]; then
+			echo "Unable to find LVM volume $DM_VG_NAME/$DM_LV_NAME"
+		fi
 	fi
-fi
+	;;
+
+/dev/*/*)
+	# Could be /dev/VG/LV; use lvs to check
+	dev="${dev#/dev/}"
+	if lvm lvs -- "$dev" >/dev/null 2>/dev/null; then
+		lvm lvchange -aly --ignorelockingfailure "$dev"
+	fi
+	;;
+esac
 
 exit 0
diff --git a/debian/initramfs-tools/lvm2/scripts/local-top/lvm2 b/debian/initramfs-tools/lvm2/scripts/local-top/lvm2
--- a/debian/initramfs-tools/lvm2/scripts/local-top/lvm2
+++ b/debian/initramfs-tools/lvm2/scripts/local-top/lvm2
@@ -24,8 +24,8 @@ activate_vg()
 		return 1
 	fi
 
-	# Take care of lilo boot arg, risky activating of all vg
 	case "$dev" in
+	# Take care of lilo boot arg, risky activating of all vg
 	fe[0-9]*)
 		lvm vgchange -aly --ignorelockingfailure
 		exit 0
@@ -35,23 +35,33 @@ activate_vg()
 		lvm vgchange -aly --ignorelockingfailure
 		exit 0
 		;;
+
+	/dev/mapper/*)
+		dev="${dev#/dev/mapper/}"
+
+		eval $(dmsetup splitname --nameprefixes --noheadings --rows "$dev")
+
+		if [ "$DM_VG_NAME" ] && [ "$DM_LV_NAME" ]; then
+			lvm lvchange -aly --ignorelockingfailure "$DM_VG_NAME/$DM_LV_NAME"
+			rc=$?
+			if [ $rc = 5 ]; then
+				echo "Unable to find LVM volume $DM_VG_NAME/$DM_LV_NAME"
+			fi
+			return 0
+		fi
+		;;
+
+	/dev/*/*)
+		# Could be /dev/VG/LV; use lvs to check
+		dev="${dev#/dev/}"
+		if lvm lvs -- "$dev" >/dev/null 2>/dev/null; then
+			lvm lvchange -aly --ignorelockingfailure "$dev"
+			return 0
+		fi
+		;;
 	esac
 
-	# Make sure that we have a d-m path
-	dev="${dev#/dev/mapper/}"
-	if [ "$dev" = "$1" ]; then
-		return 1
-	fi
-
-	eval $(dmsetup splitname --nameprefixes --noheadings --rows "$dev")
-
-	if [ "$DM_VG_NAME" ] && [ "$DM_LV_NAME" ]; then
-		lvm lvchange -aly --ignorelockingfailure "$DM_VG_NAME/$DM_LV_NAME"
-		rc=$?
-		if [ $rc = 5 ]; then
-			echo "Unable to find LVM volume $DM_VG_NAME/$DM_LV_NAME"
-		fi
-	fi
+	return 1
 }
 
 if [ ! -e /sbin/lvm ]; then
